//
//  EmojiKeyboard.swift
//

/**
 
 This demo keyboard has 24 buttons per page, which fits this
 demo app's two different grid sizes for portrait/landscape.
 It features one page of real emoji characters and four with
 image buttons, which are handled by the demo action handler.
 
 If you make any changes to this keyboard (which you should,
 play with it) the keyboard may get an uneven set of buttons,
 which the grid engine handles by adding empty dummy buttons
 at the very end.
 
 */
struct EmojiKeyboard: DemoKeyboard {
    
    init(in viewController: KeyboardParentViewController) {
        
        
        
        
        self.bottomActions = EmojiKeyboard.bottomActions(
            leftmost: EmojiKeyboard.switchAction,
            
            for: viewController)
    }
    
    
    
    let actions: [KeyboardAction] = [
        .character("☺"),
        .character("😋"),
        .character("😌"),
        .character("😍"),
        .character("😘"),
        .character("😗"),
        .character("😙"),
        .character("😚"),
        .character("😜"),
        .character("😝"),
        .character("😛"),
        .character("🤑"),
        .character("🤓"),
        .character("😎"),
        .character("🤗"),
        .character("😏"),
        .character("😶"),
        .character("😐"),
        .character("😑"),
        .character("😒"),
        .character("🙄"),
        .character("🤔"),
        .character("😳"),
        .character("😞"),
        .character("😟"),
        .character("😠"),
        .character("😡"),
        .character("😔"),
        .character("😕"),
        .character("🙁"),
        .character("😣"),
        .character("😖"),
        .character("😫"),
        .character("😩"),
        .character("😤"),
        .character("😮"),
        .character("😱"),
        .character("😨"),
        .character("😰"),
        .character("😯"),
        .character("😦"),
        .character("😧"),
        .character("😢"),
        .character("😥"),
        .character("😪"),
        .character("😓"),
        .character("😭"),
        .character("😵"),
        .character("😲"),
        .character("🤐"),
        .character("😷"),
        .character("🤒"),
        .character("🤕"),
        .character("😴"),
        .character("💤"),
        .character("💩"),
        .character("😈"),
        .character("👿"),
        .character("👹"),
        .character("👺"),
        .character("👻"),
        .character("💀"),
        .character("☠"),
        .character("👽"),
        .character("👾"),
        .character("🤖"),
        .character("😺"),
        .character("😸"),
        .character("😹"),
        .character("😻"),
        .character("😼"),
        .character("😽"),
        .character("🙀"),
        .character("😿"),
        .character("😾"),
        .character("🙌"),
        .character("👏"),
        .character("👍"),
        .character("👎"),
        .character("👊"),
        .character("✊"),
        .character("👋"),
        .character("👈"),
        .character("👉"),
        .character("👆"),
        .character("👇"),
        .character("👌"),
        .character("☝"),
        .character("✌"),
        .character("✋"),
        .character("🖐"),
        .character("👐"),
        .character("💪"),
        .character("🙏"),
        .character("🖖"),
        .character("🤘"),
        .character("🖕"),
        .character("✍"),
        .character("💅"),
        .character("👄"),
        .character("👅"),
        .character("👂"),
        .character("👃"),
        .character("👁"),
        .character("👀"),
        .character("🗣"),
        .character("👤"),
        .character("👥"),
        .character("👶"),
        .character("👦"),
        .character("👧"),
        .character("👨"),
        .character("👩"),
        .character("👱"),
        .character("👴"),
        .character("👵"),
        .character("👲"),
        .character("👳"),
        .character("👮"),
        .character("👷"),
        .character("💂"),
        .character("🎅"),
        .character("👸"),
        .character("👰"),
        .character("👼"),
        .character("🙇"),
        .character("💁"),
        .character("🙅"),
        .character("🙆"),
        .character("🙋"),
        .character("🙎"),
        .character("🙍"),
        .character("💇"),
        .character("💆"),
        .character("💃"),
        .character("👯"),
        .character("🚶"),
        .character("🏃"),
        .character("👫"),
        .character("👭"),
        .character("👬"),
        .character("💑"),
        .character("👩"),
        .character("👨"),
        .character("💏"),
        .character("👩"),
        .character("👨"),
        .character("👪"),
        .character("👨"),
        .character("👨"),
        .character("👨"),
        .character("👨"),
        .character("👩"),
        .character("👩"),
        .character("👩"),
        .character("👩"),
        .character("👩"),
        .character("👨"),
        .character("👨"),
        .character("👨"),
        .character("👨"),
        .character("👨"),
        .character("👚"),
        .character("👕"),
        .character("👖"),
        .character("👔"),
        .character("👗"),
        .character("👙"),
        .character("👘"),
        .character("💄"),
        .character("💋"),
        .character("👣"),
        .character("👠"),
        .character("👡"),
        .character("👢"),
        .character("👞"),
        .character("👟"),
        .character("👒"),
        .character("🎩"),
        .character("🎓"),
        .character("👑"),
        .character("⛑"),
        .character("🎒"),
        .character("👝"),
        .character("👛"),
        .character("👜"),
        .character("💼"),
        .character("👓"),
        .character("🕶"),
        .character("💍"),
        .character("🌂"),
        .character("🐶"),
        .character("🐱"),
        .character("🐭"),
        .character("🐹"),
        .character("🐰"),
        .character("🐻"),
        .character("🐼"),
        .character("🐨"),
        .character("🐯"),
        .character("🦁"),
        .character("🐮"),
        .character("🐷"),
        .character("🐽"),
        .character("🐸"),
        .character("🐙"),
        .character("🐵"),
        .character("🙈"),
        .character("🙉"),
        .character("🙊"),
        .character("🐒"),
        .character("🐔"),
        .character("🐧"),
        .character("🐦"),
        .character("🐤"),
        .character("🐣"),
        .character("🐥"),
        .character("🐺"),
        .character("🐗"),
        .character("🐴"),
        .character("🦄"),
        .character("🐝"),
        .character("🐛"),
        .character("🐌"),
        .character("🐞"),
        .character("🐜"),
        .character("🕷"),
        .character("🦂"),
        .character("🦀"),
        .character("🐍"),
        .character("🐢"),
        .character("🐠"),
        .character("🐟"),
        .character("🐡"),
        .character("🐬"),
        .character("🐳"),
        .character("🐋"),
        .character("🐊"),
        .character("🐆"),
        .character("🐅"),
        .character("🐃"),
        .character("🐂"),
        .character("🐄"),
        .character("🐪"),
        .character("🐫"),
        .character("🐘"),
        .character("🐐"),
        .character("🐏"),
        .character("🐑"),
        .character("🐎"),
        .character("🐖"),
        .character("🐀"),
        .character("🐁"),
        .character("🐓"),
        .character("🦃"),
        .character("🕊"),
        .character("🐕"),
        .character("🐩"),
        .character("🐈"),
        .character("🐇"),
        .character("🐿"),
        .character("🐾"),
        .character("🐉"),
        .character("🐲"),
        .character("🌵"),
        .character("🎄"),
        .character("🌲"),
        .character("🌳"),
        .character("🌴"),
        .character("🌱"),
        .character("🌿"),
        .character("☘"),
        .character("🍀"),
        .character("🎍"),
        .character("🎋"),
        .character("🍃"),
        .character("🍂"),
        .character("🍁"),
        .character("🌾"),
        .character("🌺"),
        .character("🌻"),
        .character("🌹"),
        .character("🌷"),
        .character("🌼"),
        .character("🌸"),
        .character("💐"),
        .character("🍄"),
        .character("🌰"),
        .character("🎃"),
        .character("🐚"),
        .character("🕸"),
        .character("🌎"),
        .character("🌍"),
        .character("🌏"),
        .character("🌕"),
        .character("🌖"),
        .character("🌗"),
        .character("🌘"),
        .character("🌑"),
        .character("🌒"),
        .character("🌓"),
        .character("🌔"),
        .character("🌚"),
        .character("🌝"),
        .character("🌛"),
        .character("🌜"),
        .character("🌞"),
        .character("🌙"),
        .character("⭐"),
        .character("🌟"),
        .character("💫"),
        .character("✨"),
        .character("☄"),
        .character("☀"),
        .character("🌤"),
        .character("⛅"),
        .character("🌥"),
        .character("🌦"),
        .character("☁"),
        .character("🌧"),
        .character("⛈"),
        .character("🌩"),
        .character("⚡"),
        .character("🔥"),
        .character("💥"),
        .character("❄"),
        .character("🌨"),
        .character("☃"),
        .character("⛄"),
        .character("🌬"),
        .character("💨"),
        .character("🌪"),
        .character("🌫"),
        .character("☂"),
        .character("☔"),
        .character("💧"),
        .character("💦"),
        .character("🌊"),
        .character("🍏"),
        .character("🍎"),
        .character("🍐"),
        .character("🍊"),
        .character("🍋"),
        .character("🍌"),
        .character("🍉"),
        .character("🍇"),
        .character("🍓")
    ]
    
    let bottomActions: KeyboardActionRow
}

private extension EmojiKeyboard {
    
    /*static var switchAction: KeyboardAction {
        .switchToKeyboard(.alphabetic(uppercased: false))
    }*/
    
    static func actions(
        uppercased: Bool,
        in viewController: KeyboardParentViewController) -> KeyboardActionRows {
        KeyboardActionRows
            .from(characters(uppercased: uppercased))
            .addingSideActions(uppercased: uppercased)
            .appending(bottomActions(leftmost: switchAction, for: viewController))
    }
    
    static let characters: [[String]] = [
        ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
        ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ñ"],
        ["z", "x", "c", "v", "b", "n", "m"]
    ]
    
    static func characters(uppercased: Bool) -> [[String]] {
        uppercased ? characters.uppercased() : characters
    }
    
    static var switchAction: KeyboardAction {
        .switchToKeyboard(.numeric)
    }
}


private extension Sequence where Iterator.Element == KeyboardActionRow {
    
    func addingSideActions(uppercased: Bool) -> [Iterator.Element] {
        var result = map { $0 }
        result[2].insert(uppercased ? .shiftDown : .shift, at: 0)
        result[2].insert(.none, at: 1)
        result[2].append(.none)
        result[2].append(.backspace)
        return result
    }
}
